#!/bin/sh
set -e
PREFIX="${DOLPHIN_DEV_PREFIX:-$PWD/install}"
cmake -G Ninja -B build \
  -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DKDE_INSTALL_LIBDIR=lib \
  -DKDE_INSTALL_INCLUDEDIR=include \
  -DKDE_INSTALL_CMAKEPACKAGEDIR=lib/cmake \
  -DKDE_INSTALL_PLUGINDIR=lib/qt-6/plugins \
  -DKDE_INSTALL_QMLDIR=lib/qt-6/qml \
  -DKDE_INSTALL_LIBEXECDIR=libexec \
  .
